-- Generated by tools/build_basic_data.py from the clean V44 manifest.
-- Run only after Flyway V44+. No users, credentials or business data are copied.
-- Existing populated CMS data is a no-op; partially empty CMS data is rejected.
BEGIN;
SET LOCAL search_path TO cleverchat_dev, public;
SET LOCAL lock_timeout = '10s';
LOCK TABLE tb_role, tb_auth, tb_menu, tb_code, tb_auth_menu_adm IN SHARE ROW EXCLUSIVE MODE;
DO $basic_data$
DECLARE nonempty_tables integer;
BEGIN
  SELECT (EXISTS(SELECT 1 FROM tb_auth))::int + (EXISTS(SELECT 1 FROM tb_menu))::int
       + (EXISTS(SELECT 1 FROM tb_code))::int + (EXISTS(SELECT 1 FROM tb_auth_menu_adm))::int
  INTO nonempty_tables;
  IF nonempty_tables = 4 THEN
    RAISE NOTICE 'Existing CMS data retained. Run check-basic-data.sql to inspect it.';
    RETURN;
  ELSIF nonempty_tables <> 0 THEN
    RAISE EXCEPTION 'Partially populated CMS tables: no changes made. Review/restore the missing data.';
  END IF;

  INSERT INTO tb_role(code,description)
  SELECT v.code,v.description FROM (VALUES
    ('ADMIN', '관리자'),
    ('OPERATOR', '운영자'),
    ('USER', '일반 사용자')) v(code,description)
  WHERE NOT EXISTS(SELECT 1 FROM tb_role r WHERE r.code=v.code)
  ON CONFLICT(code) DO NOTHING;

  INSERT INTO tb_auth(auth_no,auth_nm,auth_dc,sort_order,use_yn,frst_regr_empno,lst_chgr_empno) VALUES
    (1, 'ADMIN', '관리자', 1, 'Y', 'basic-data', 'basic-data'),
    (2, 'OPERATOR', '운영자', 2, 'Y', 'basic-data', 'basic-data'),
    (3, 'USER', '일반 사용자', 3, 'Y', 'basic-data', 'basic-data');

  INSERT INTO tb_menu(menu_no,p_menu_no,menu_nm,menu_type,menu_depth,sort_order,target_blank_yn,menu_url,open_yn,use_yn,frst_regr_empno,lst_chgr_empno) VALUES
    (1, 0, 'Dashboard', 'ADM', 1, 10, 'N', '/admin', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 0, 'Scenario', 'ADM', 1, 20, 'N', NULL, 'Y', 'Y', 'basic-data', 'basic-data'),
    (3, 0, 'Chat operations', 'ADM', 1, 30, 'N', NULL, 'Y', 'Y', 'basic-data', 'basic-data'),
    (4, 0, 'Search and crawl', 'ADM', 1, 40, 'N', NULL, 'Y', 'Y', 'basic-data', 'basic-data'),
    (5, 0, 'Operations', 'ADM', 1, 50, 'N', NULL, 'Y', 'Y', 'basic-data', 'basic-data'),
    (6, 0, 'CMS management', 'ADM', 1, 60, 'N', NULL, 'Y', 'Y', 'basic-data', 'basic-data'),
    (7, 2, 'Scenario list', 'ADM', 2, 10, 'N', '/admin/scenarios', 'Y', 'Y', 'basic-data', 'basic-data'),
    (8, 3, 'Recommended questions', 'ADM', 2, 40, 'N', '/admin/chat/recommendations', 'Y', 'Y', 'basic-data', 'basic-data'),
    (9, 3, 'Feedback', 'ADM', 2, 30, 'N', '/admin/chat/feedback', 'Y', 'Y', 'basic-data', 'basic-data'),
    (10, 3, 'Failure queue', 'ADM', 2, 20, 'N', '/admin/chat/failures', 'Y', 'Y', 'basic-data', 'basic-data'),
    (11, 3, 'Chat sessions', 'ADM', 2, 10, 'N', '/admin/chat/sessions', 'Y', 'Y', 'basic-data', 'basic-data'),
    (12, 4, 'Crawl runs', 'ADM', 2, 60, 'N', '/admin/crawl-runs', 'N', 'Y', 'basic-data', 'basic-data'),
    (13, 4, 'Crawl documents', 'ADM', 2, 50, 'N', '/admin/crawl-documents', 'N', 'Y', 'basic-data', 'basic-data'),
    (14, 4, '크롤링 관리', 'ADM', 2, 40, 'N', '/admin/crawl-targets', 'Y', 'Y', 'basic-data', 'basic-data'),
    (15, 4, 'Popular queries', 'ADM', 2, 30, 'N', '/admin/search/popular', 'Y', 'Y', 'basic-data', 'basic-data'),
    (16, 4, 'PII block logs', 'ADM', 2, 20, 'N', '/admin/search/blocks', 'Y', 'Y', 'basic-data', 'basic-data'),
    (17, 4, 'Search logs', 'ADM', 2, 10, 'N', '/admin/search/logs', 'Y', 'Y', 'basic-data', 'basic-data'),
    (18, 5, 'Notifications', 'ADM', 2, 40, 'N', '/admin/notifications', 'Y', 'Y', 'basic-data', 'basic-data'),
    (19, 5, 'Notices', 'ADM', 2, 30, 'N', '/admin/notices', 'Y', 'Y', 'basic-data', 'basic-data'),
    (20, 5, 'Audit logs', 'ADM', 2, 20, 'N', '/admin/audit-logs', 'Y', 'Y', 'basic-data', 'basic-data'),
    (21, 5, 'Statistics', 'ADM', 2, 10, 'N', '/admin/statistics', 'Y', 'Y', 'basic-data', 'basic-data'),
    (22, 6, 'Permission management', 'ADM', 2, 30, 'N', '/admin/manage/permissions', 'Y', 'Y', 'basic-data', 'basic-data'),
    (23, 6, 'Menu management', 'ADM', 2, 20, 'N', '/admin/manage/menus', 'Y', 'Y', 'basic-data', 'basic-data'),
    (24, 6, 'Code management', 'ADM', 2, 10, 'N', '/admin/manage/codes', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1000, 2, '시나리오 정렬', 'ADM', 2, 20, 'N', '/admin/scenarios/order', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1001, 6, '관리자 IP 허용목록', 'ADM', 2, 40, 'N', '/admin/manage/ip-whitelist', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1002, 6, '시스템 설정', 'ADM', 2, 50, 'N', '/admin/system-settings', 'Y', 'Y', 'basic-data', 'basic-data');

  INSERT INTO tb_code(code_no,p_code_no,code_group,code_nm,code_val,code_dc,code_depth,sort_order,use_yn,frst_regr_empno,lst_chgr_empno) VALUES
    (1, 0, 'SYSTEM_CODE', '시스템코드', 'GROUP', 'CleverChat 시스템 공통코드', 1, 10, 'Y', 'basic-data', 'basic-data'),
    (2, 1, 'NOTICE_STATUS', '공지 노출 상태', 'GROUP', '공지사항 노출 여부', 2, 10, 'Y', 'basic-data', 'basic-data'),
    (3, 1, 'NOTIFICATION_CHANNEL_TYPE', '알림 채널 유형', 'GROUP', '운영 알림 발송 채널', 2, 20, 'Y', 'basic-data', 'basic-data'),
    (4, 1, 'CRAWL_STATUS', '크롤링 결과 상태', 'GROUP', '크롤 문서 및 실행 결과', 2, 30, 'Y', 'basic-data', 'basic-data'),
    (5, 1, 'SCENARIO_STATUS', '시나리오 상태', 'GROUP', '시나리오 생명주기 상태', 2, 40, 'Y', 'basic-data', 'basic-data'),
    (6, 1, 'SCENARIO_VERSION_STATUS', '시나리오 버전 상태', 'GROUP', '시나리오 버전 생명주기 상태', 2, 50, 'Y', 'basic-data', 'basic-data'),
    (7, 1, 'SCENARIO_NODE_TYPE', '시나리오 노드 유형', 'GROUP', '시나리오 그래프 노드 유형', 2, 60, 'Y', 'basic-data', 'basic-data'),
    (8, 1, 'SCENARIO_LINK_TYPE', '시나리오 링크 유형', 'GROUP', '답변 링크 이동 유형', 2, 70, 'Y', 'basic-data', 'basic-data'),
    (9, 1, 'CHAT_SESSION_STATE', '채팅 세션 상태', 'GROUP', '채팅 세션 진행 상태', 2, 80, 'Y', 'basic-data', 'basic-data'),
    (10, 1, 'CHAT_SESSION_TYPE', '채팅 세션 유형', 'GROUP', '시나리오/검색 세션 구분', 2, 90, 'Y', 'basic-data', 'basic-data'),
    (11, 1, 'CHAT_MESSAGE_DIRECTION', '채팅 메시지 방향', 'GROUP', '메시지 작성 주체', 2, 100, 'Y', 'basic-data', 'basic-data'),
    (12, 1, 'CHAT_FEEDBACK_RATING', '채팅 답변 평가', 'GROUP', '답변 만족도 평가', 2, 110, 'Y', 'basic-data', 'basic-data'),
    (13, 1, 'CHAT_FAILURE_REASON', '채팅 실패 사유', 'GROUP', '채팅 처리 실패 분류', 2, 120, 'Y', 'basic-data', 'basic-data'),
    (14, 1, 'SEARCH_SOURCE', '검색 요청 출처', 'GROUP', '통합검색 호출 출처', 2, 130, 'Y', 'basic-data', 'basic-data'),
    (15, 1, 'CRAWL_SCHEDULE_MODE', '크롤링 일정 방식', 'GROUP', '크롤링 실행 주기 방식', 2, 140, 'Y', 'basic-data', 'basic-data'),
    (16, 1, 'CRAWL_JOB_TRIGGER_TYPE', '크롤링 작업 실행 유형', 'GROUP', '브라우저 크롤링 작업 실행 원인', 2, 150, 'Y', 'basic-data', 'basic-data'),
    (17, 1, 'CRAWL_JOB_STATUS', '크롤링 작업 상태', 'GROUP', '브라우저 크롤링 작업 진행 상태', 2, 160, 'Y', 'basic-data', 'basic-data'),
    (18, 1, 'NOTIFICATION_EVENT_SEVERITY', '알림 심각도', 'GROUP', '운영 알림 중요도', 2, 170, 'Y', 'basic-data', 'basic-data'),
    (19, 1, 'NOTIFICATION_EVENT_STATUS', '알림 발송 상태', 'GROUP', '운영 알림 발송 처리 상태', 2, 180, 'Y', 'basic-data', 'basic-data'),
    (20, 1, 'CRAWL_NATIVE_LIB_STATUS', '크롤러 라이브러리 상태', 'GROUP', '브라우저 네이티브 라이브러리 상태', 2, 190, 'Y', 'basic-data', 'basic-data'),
    (21, 2, 'NOTICE_ENABLED', '노출', 'ENABLED', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (22, 2, 'NOTICE_DISABLED', '미노출', 'DISABLED', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (23, 3, 'CHANNEL_WEBHOOK', '웹훅', 'WEBHOOK', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (24, 3, 'CHANNEL_SLACK_WEBHOOK', '슬랙 웹훅', 'SLACK_WEBHOOK', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (25, 3, 'CHANNEL_EMAIL_SMTP', '이메일 SMTP', 'EMAIL_SMTP', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (26, 4, 'CRAWL_SUCCESS', '성공', 'SUCCESS', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (27, 4, 'CRAWL_FAILED', '실패', 'FAILED', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (28, 4, 'CRAWL_DUPLICATE', '중복', 'DUPLICATE', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (29, 5, 'SCENARIO_DRAFT', '작성 중', 'DRAFT', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (30, 5, 'SCENARIO_ACTIVE', '활성', 'ACTIVE', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (31, 5, 'SCENARIO_INACTIVE', '비활성', 'INACTIVE', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (32, 5, 'SCENARIO_DELETED', '삭제', 'DELETED', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (33, 6, 'SCENARIO_VERSION_DRAFT', '초안', 'DRAFT', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (34, 6, 'SCENARIO_VERSION_PUBLISHED', '게시', 'PUBLISHED', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (35, 6, 'SCENARIO_VERSION_ARCHIVED', '보관', 'ARCHIVED', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (36, 7, 'NODE_QUESTION', '질문', 'QUESTION', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (37, 7, 'NODE_ANSWER', '답변', 'ANSWER', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (38, 7, 'NODE_BRANCH', '분기', 'BRANCH', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (39, 7, 'NODE_END', '종료', 'END', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (40, 8, 'LINK_EXTERNAL', '외부 링크', 'EXTERNAL', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (41, 8, 'LINK_INTERNAL', '내부 링크', 'INTERNAL', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (42, 8, 'LINK_DOWNLOAD', '파일 다운로드', 'DOWNLOAD', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (43, 9, 'CHAT_STATE_ACTIVE', '진행 중', 'ACTIVE', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (44, 9, 'CHAT_STATE_COMPLETED', '완료', 'COMPLETED', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (45, 9, 'CHAT_STATE_ABANDONED', '중단', 'ABANDONED', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (46, 9, 'CHAT_STATE_EXPIRED', '만료', 'EXPIRED', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (47, 10, 'CHAT_TYPE_SCENARIO', '시나리오 상담', 'SCENARIO', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (48, 10, 'CHAT_TYPE_SEARCH', '통합검색', 'SEARCH', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (49, 11, 'MESSAGE_USER', '사용자', 'USER', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (50, 11, 'MESSAGE_BOT', '챗봇', 'BOT', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (51, 11, 'MESSAGE_SYSTEM', '시스템', 'SYSTEM', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (52, 12, 'FEEDBACK_UP', '만족', 'UP', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (53, 12, 'FEEDBACK_DOWN', '불만족', 'DOWN', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (54, 13, 'CHAT_FAIL_NO_MATCH', '검색 결과 없음', 'NO_MATCH', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (55, 13, 'CHAT_FAIL_EXPIRED', '세션 만료', 'EXPIRED', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (56, 13, 'CHAT_FAIL_INVALID_OPTION', '잘못된 선택', 'INVALID_OPTION', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (57, 13, 'CHAT_FAIL_SYSTEM_ERROR', '시스템 오류', 'SYSTEM_ERROR', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (58, 13, 'CHAT_FAIL_PII_BLOCKED', '개인정보 차단', 'PII_BLOCKED', NULL, 3, 50, 'Y', 'basic-data', 'basic-data'),
    (59, 13, 'CHAT_FAIL_RATE_LIMITED', '요청 한도 초과', 'RATE_LIMITED', NULL, 3, 60, 'Y', 'basic-data', 'basic-data'),
    (60, 14, 'SEARCH_CHAT_FALLBACK', '챗봇 대체 검색', 'CHAT_FALLBACK', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (61, 14, 'SEARCH_ADMIN_TEST', '관리자 테스트', 'ADMIN_TEST', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (62, 14, 'SEARCH_API', '외부 API', 'API', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (63, 15, 'CRAWL_SCHEDULE_INTERVAL', '주기 실행', 'INTERVAL', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (64, 15, 'CRAWL_SCHEDULE_CRON', 'Cron 실행', 'CRON', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (65, 16, 'CRAWL_TRIGGER_MANUAL', '수동 실행', 'MANUAL', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (66, 16, 'CRAWL_TRIGGER_SCHEDULE', '예약 실행', 'SCHEDULE', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (67, 17, 'CRAWL_JOB_PENDING', '대기', 'PENDING', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (68, 17, 'CRAWL_JOB_RUNNING', '실행 중', 'RUNNING', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (69, 17, 'CRAWL_JOB_SUCCESS', '성공', 'SUCCESS', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (70, 17, 'CRAWL_JOB_FAILED', '실패', 'FAILED', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (71, 17, 'CRAWL_JOB_CANCELED', '취소', 'CANCELED', NULL, 3, 50, 'Y', 'basic-data', 'basic-data'),
    (72, 18, 'NOTIFY_SEVERITY_INFO', '정보', 'INFO', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (73, 18, 'NOTIFY_SEVERITY_WARN', '경고', 'WARN', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (74, 18, 'NOTIFY_SEVERITY_ERROR', '오류', 'ERROR', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (75, 19, 'NOTIFY_STATUS_PENDING', '대기', 'PENDING', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (76, 19, 'NOTIFY_STATUS_SENT', '발송 완료', 'SENT', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (77, 19, 'NOTIFY_STATUS_RETRY', '재시도', 'RETRY', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (78, 19, 'NOTIFY_STATUS_FAILED', '발송 실패', 'FAILED', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (79, 20, 'NATIVE_LIB_VERIFIED', '검증 완료', 'VERIFIED', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (80, 20, 'NATIVE_LIB_ACTIVE', '적용 중', 'ACTIVE', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (81, 20, 'NATIVE_LIB_REJECTED', '반려', 'REJECTED', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (82, 1, 'CRAWL_FAILURE_CODE', '크롤링 실패 코드', 'GROUP', '크롤링 실패 원인 분류', 2, 125, 'Y', 'basic-data', 'basic-data'),
    (83, 82, 'CRAWL_FAIL_ROBOTS_BLOCKED', 'robots.txt 차단', 'ROBOTS_BLOCKED', NULL, 3, 10, 'Y', 'basic-data', 'basic-data'),
    (84, 82, 'CRAWL_FAIL_HTTP_ERROR', 'HTTP 오류', 'HTTP_ERROR', NULL, 3, 20, 'Y', 'basic-data', 'basic-data'),
    (85, 82, 'CRAWL_FAIL_TIMEOUT', '시간 초과', 'TIMEOUT', NULL, 3, 30, 'Y', 'basic-data', 'basic-data'),
    (86, 82, 'CRAWL_FAIL_PARSE_ERROR', '본문 분석 오류', 'PARSE_ERROR', NULL, 3, 40, 'Y', 'basic-data', 'basic-data'),
    (87, 82, 'CRAWL_FAIL_DUP_HASH', '중복 문서', 'DUP_HASH', NULL, 3, 50, 'Y', 'basic-data', 'basic-data'),
    (88, 82, 'CRAWL_FAIL_FETCH_ERROR', '수집 오류', 'FETCH_ERROR', NULL, 3, 60, 'Y', 'basic-data', 'basic-data'),
    (89, 82, 'CRAWL_FAIL_NOT_HTML', 'HTML 아님', 'NOT_HTML', NULL, 3, 70, 'Y', 'basic-data', 'basic-data'),
    (90, 82, 'CRAWL_FAIL_URL_BLOCKED', 'URL 차단', 'URL_BLOCKED', NULL, 3, 80, 'Y', 'basic-data', 'basic-data'),
    (91, 82, 'CRAWL_FAIL_SCHEDULE_INVALID', '일정 설정 오류', 'SCHEDULE_INVALID', NULL, 3, 90, 'Y', 'basic-data', 'basic-data'),
    (92, 82, 'CRAWL_FAIL_SYSTEM_ERROR', '시스템 오류', 'SYSTEM_ERROR', NULL, 3, 100, 'Y', 'basic-data', 'basic-data'),
    (93, 82, 'CRAWL_FAIL_BROWSER_ERROR', '브라우저 오류', 'BROWSER_ERROR', NULL, 3, 110, 'Y', 'basic-data', 'basic-data'),
    (94, 82, 'CRAWL_FAIL_EXPORT_ERROR', 'JSON 파일 저장 오류', 'EXPORT_ERROR', NULL, 3, 120, 'Y', 'basic-data', 'basic-data');

  INSERT INTO tb_auth_menu_adm(auth_no,menu_no,p_menu_no,select_yn,insert_yn,update_yn,delete_yn,proc_yn,use_yn,frst_regr_empno,lst_chgr_empno) VALUES
    (1, 1, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 2, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 3, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 4, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 5, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 6, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 7, 2, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 8, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 9, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 10, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 11, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 12, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 13, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 14, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 15, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 16, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 17, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 18, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 19, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 20, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 21, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 22, 6, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 23, 6, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 24, 6, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 1000, 2, 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 1001, 6, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (1, 1002, 6, 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 1, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 2, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 3, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 4, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 5, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 6, 0, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 7, 2, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 8, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 9, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 10, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 11, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 12, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 13, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 14, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 15, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 16, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 17, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 18, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 19, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 20, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 21, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'basic-data', 'basic-data'),
    (2, 1000, 2, 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'basic-data', 'basic-data');

  INSERT INTO tb_system_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;

  PERFORM setval('seq_tb_auth_auth_no', GREATEST(s.last_value,(SELECT max(auth_no) FROM tb_auth)),
      s.is_called OR (SELECT max(auth_no) FROM tb_auth) >= s.last_value) FROM seq_tb_auth_auth_no s;
  PERFORM setval('seq_tb_menu_menu_no', GREATEST(s.last_value,(SELECT max(menu_no) FROM tb_menu)),
      s.is_called OR (SELECT max(menu_no) FROM tb_menu) >= s.last_value) FROM seq_tb_menu_menu_no s;
  PERFORM setval('tb_code_code_no_seq', GREATEST(s.last_value,(SELECT max(code_no) FROM tb_code)),
      s.is_called OR (SELECT max(code_no) FROM tb_code) >= s.last_value) FROM tb_code_code_no_seq s;
  RAISE NOTICE 'Default menus/codes/roles/permissions initialized. User accounts were not modified.';
END $basic_data$;
COMMIT;
