-- Read-only validation against the clean V44 baseline. Never restores disabled permissions.
-- Existing customized data may differ; review differences, do not blindly reseed it.
BEGIN READ ONLY;
SET LOCAL search_path TO cleverchat_dev, public;
WITH required_roles(code) AS (VALUES
    ('ADMIN'),
    ('OPERATOR'),
    ('USER')),
required_menus(url) AS (VALUES
    ('/admin'),
    ('/admin/scenarios'),
    ('/admin/chat/recommendations'),
    ('/admin/chat/feedback'),
    ('/admin/chat/failures'),
    ('/admin/chat/sessions'),
    ('/admin/crawl-runs'),
    ('/admin/crawl-documents'),
    ('/admin/crawl-targets'),
    ('/admin/search/popular'),
    ('/admin/search/blocks'),
    ('/admin/search/logs'),
    ('/admin/notifications'),
    ('/admin/notices'),
    ('/admin/audit-logs'),
    ('/admin/statistics'),
    ('/admin/manage/permissions'),
    ('/admin/manage/menus'),
    ('/admin/manage/codes'),
    ('/admin/scenarios/order'),
    ('/admin/manage/ip-whitelist'),
    ('/admin/system-settings')),
required_groups(group_key) AS (VALUES
    ('SYSTEM_CODE'),
    ('NOTICE_STATUS'),
    ('NOTIFICATION_CHANNEL_TYPE'),
    ('CRAWL_STATUS'),
    ('SCENARIO_STATUS'),
    ('SCENARIO_VERSION_STATUS'),
    ('SCENARIO_NODE_TYPE'),
    ('SCENARIO_LINK_TYPE'),
    ('CHAT_SESSION_STATE'),
    ('CHAT_SESSION_TYPE'),
    ('CHAT_MESSAGE_DIRECTION'),
    ('CHAT_FEEDBACK_RATING'),
    ('CHAT_FAILURE_REASON'),
    ('SEARCH_SOURCE'),
    ('CRAWL_SCHEDULE_MODE'),
    ('CRAWL_JOB_TRIGGER_TYPE'),
    ('CRAWL_JOB_STATUS'),
    ('NOTIFICATION_EVENT_SEVERITY'),
    ('NOTIFICATION_EVENT_STATUS'),
    ('CRAWL_NATIVE_LIB_STATUS'),
    ('CRAWL_FAILURE_CODE')),
required_values(parent_key,code_key,code_value) AS (VALUES
    ('NOTICE_STATUS', 'NOTICE_ENABLED', 'ENABLED'),
    ('NOTICE_STATUS', 'NOTICE_DISABLED', 'DISABLED'),
    ('NOTIFICATION_CHANNEL_TYPE', 'CHANNEL_WEBHOOK', 'WEBHOOK'),
    ('NOTIFICATION_CHANNEL_TYPE', 'CHANNEL_SLACK_WEBHOOK', 'SLACK_WEBHOOK'),
    ('NOTIFICATION_CHANNEL_TYPE', 'CHANNEL_EMAIL_SMTP', 'EMAIL_SMTP'),
    ('CRAWL_STATUS', 'CRAWL_SUCCESS', 'SUCCESS'),
    ('CRAWL_STATUS', 'CRAWL_FAILED', 'FAILED'),
    ('CRAWL_STATUS', 'CRAWL_DUPLICATE', 'DUPLICATE'),
    ('SCENARIO_STATUS', 'SCENARIO_DRAFT', 'DRAFT'),
    ('SCENARIO_STATUS', 'SCENARIO_ACTIVE', 'ACTIVE'),
    ('SCENARIO_STATUS', 'SCENARIO_INACTIVE', 'INACTIVE'),
    ('SCENARIO_STATUS', 'SCENARIO_DELETED', 'DELETED'),
    ('SCENARIO_VERSION_STATUS', 'SCENARIO_VERSION_DRAFT', 'DRAFT'),
    ('SCENARIO_VERSION_STATUS', 'SCENARIO_VERSION_PUBLISHED', 'PUBLISHED'),
    ('SCENARIO_VERSION_STATUS', 'SCENARIO_VERSION_ARCHIVED', 'ARCHIVED'),
    ('SCENARIO_NODE_TYPE', 'NODE_QUESTION', 'QUESTION'),
    ('SCENARIO_NODE_TYPE', 'NODE_ANSWER', 'ANSWER'),
    ('SCENARIO_NODE_TYPE', 'NODE_BRANCH', 'BRANCH'),
    ('SCENARIO_NODE_TYPE', 'NODE_END', 'END'),
    ('SCENARIO_LINK_TYPE', 'LINK_EXTERNAL', 'EXTERNAL'),
    ('SCENARIO_LINK_TYPE', 'LINK_INTERNAL', 'INTERNAL'),
    ('SCENARIO_LINK_TYPE', 'LINK_DOWNLOAD', 'DOWNLOAD'),
    ('CHAT_SESSION_STATE', 'CHAT_STATE_ACTIVE', 'ACTIVE'),
    ('CHAT_SESSION_STATE', 'CHAT_STATE_COMPLETED', 'COMPLETED'),
    ('CHAT_SESSION_STATE', 'CHAT_STATE_ABANDONED', 'ABANDONED'),
    ('CHAT_SESSION_STATE', 'CHAT_STATE_EXPIRED', 'EXPIRED'),
    ('CHAT_SESSION_TYPE', 'CHAT_TYPE_SCENARIO', 'SCENARIO'),
    ('CHAT_SESSION_TYPE', 'CHAT_TYPE_SEARCH', 'SEARCH'),
    ('CHAT_MESSAGE_DIRECTION', 'MESSAGE_USER', 'USER'),
    ('CHAT_MESSAGE_DIRECTION', 'MESSAGE_BOT', 'BOT'),
    ('CHAT_MESSAGE_DIRECTION', 'MESSAGE_SYSTEM', 'SYSTEM'),
    ('CHAT_FEEDBACK_RATING', 'FEEDBACK_UP', 'UP'),
    ('CHAT_FEEDBACK_RATING', 'FEEDBACK_DOWN', 'DOWN'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_NO_MATCH', 'NO_MATCH'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_EXPIRED', 'EXPIRED'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_INVALID_OPTION', 'INVALID_OPTION'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_SYSTEM_ERROR', 'SYSTEM_ERROR'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_PII_BLOCKED', 'PII_BLOCKED'),
    ('CHAT_FAILURE_REASON', 'CHAT_FAIL_RATE_LIMITED', 'RATE_LIMITED'),
    ('SEARCH_SOURCE', 'SEARCH_CHAT_FALLBACK', 'CHAT_FALLBACK'),
    ('SEARCH_SOURCE', 'SEARCH_ADMIN_TEST', 'ADMIN_TEST'),
    ('SEARCH_SOURCE', 'SEARCH_API', 'API'),
    ('CRAWL_SCHEDULE_MODE', 'CRAWL_SCHEDULE_INTERVAL', 'INTERVAL'),
    ('CRAWL_SCHEDULE_MODE', 'CRAWL_SCHEDULE_CRON', 'CRON'),
    ('CRAWL_JOB_TRIGGER_TYPE', 'CRAWL_TRIGGER_MANUAL', 'MANUAL'),
    ('CRAWL_JOB_TRIGGER_TYPE', 'CRAWL_TRIGGER_SCHEDULE', 'SCHEDULE'),
    ('CRAWL_JOB_STATUS', 'CRAWL_JOB_PENDING', 'PENDING'),
    ('CRAWL_JOB_STATUS', 'CRAWL_JOB_RUNNING', 'RUNNING'),
    ('CRAWL_JOB_STATUS', 'CRAWL_JOB_SUCCESS', 'SUCCESS'),
    ('CRAWL_JOB_STATUS', 'CRAWL_JOB_FAILED', 'FAILED'),
    ('CRAWL_JOB_STATUS', 'CRAWL_JOB_CANCELED', 'CANCELED'),
    ('NOTIFICATION_EVENT_SEVERITY', 'NOTIFY_SEVERITY_INFO', 'INFO'),
    ('NOTIFICATION_EVENT_SEVERITY', 'NOTIFY_SEVERITY_WARN', 'WARN'),
    ('NOTIFICATION_EVENT_SEVERITY', 'NOTIFY_SEVERITY_ERROR', 'ERROR'),
    ('NOTIFICATION_EVENT_STATUS', 'NOTIFY_STATUS_PENDING', 'PENDING'),
    ('NOTIFICATION_EVENT_STATUS', 'NOTIFY_STATUS_SENT', 'SENT'),
    ('NOTIFICATION_EVENT_STATUS', 'NOTIFY_STATUS_RETRY', 'RETRY'),
    ('NOTIFICATION_EVENT_STATUS', 'NOTIFY_STATUS_FAILED', 'FAILED'),
    ('CRAWL_NATIVE_LIB_STATUS', 'NATIVE_LIB_VERIFIED', 'VERIFIED'),
    ('CRAWL_NATIVE_LIB_STATUS', 'NATIVE_LIB_ACTIVE', 'ACTIVE'),
    ('CRAWL_NATIVE_LIB_STATUS', 'NATIVE_LIB_REJECTED', 'REJECTED'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_ROBOTS_BLOCKED', 'ROBOTS_BLOCKED'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_HTTP_ERROR', 'HTTP_ERROR'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_TIMEOUT', 'TIMEOUT'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_PARSE_ERROR', 'PARSE_ERROR'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_DUP_HASH', 'DUP_HASH'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_FETCH_ERROR', 'FETCH_ERROR'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_NOT_HTML', 'NOT_HTML'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_URL_BLOCKED', 'URL_BLOCKED'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_SCHEDULE_INVALID', 'SCHEDULE_INVALID'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_SYSTEM_ERROR', 'SYSTEM_ERROR'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_BROWSER_ERROR', 'BROWSER_ERROR'),
    ('CRAWL_FAILURE_CODE', 'CRAWL_FAIL_EXPORT_ERROR', 'EXPORT_ERROR')),
required_grants(auth_name,menu_url,root_name,select_yn,insert_yn,update_yn,delete_yn,proc_yn) AS (VALUES
    ('ADMIN', '/admin', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', NULL, 'Scenario', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', NULL, 'Chat operations', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', NULL, 'Search and crawl', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', NULL, 'Operations', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', NULL, 'CMS management', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/scenarios', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/chat/recommendations', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/chat/feedback', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/chat/failures', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/chat/sessions', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/crawl-runs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/crawl-documents', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/crawl-targets', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/search/popular', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/search/blocks', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/search/logs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/notifications', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/notices', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/audit-logs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/statistics', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/manage/permissions', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/manage/menus', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/manage/codes', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/scenarios/order', NULL, 'Y', 'N', 'Y', 'N', 'Y'),
    ('ADMIN', '/admin/manage/ip-whitelist', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('ADMIN', '/admin/system-settings', NULL, 'Y', 'N', 'Y', 'N', 'Y'),
    ('OPERATOR', '/admin', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', NULL, 'Scenario', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', NULL, 'Chat operations', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', NULL, 'Search and crawl', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', NULL, 'Operations', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', NULL, 'CMS management', 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/scenarios', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/chat/recommendations', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/chat/feedback', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/chat/failures', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/chat/sessions', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/crawl-runs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/crawl-documents', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/crawl-targets', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/search/popular', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/search/blocks', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/search/logs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/notifications', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/notices', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/audit-logs', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/statistics', NULL, 'Y', 'Y', 'Y', 'Y', 'Y'),
    ('OPERATOR', '/admin/scenarios/order', NULL, 'Y', 'N', 'Y', 'N', 'Y'))
SELECT jsonb_build_object('baseline','V44','counts',jsonb_build_object(
  'tb_role',(SELECT count(*) FROM tb_role),
  'tb_auth',(SELECT count(*) FROM tb_auth),
  'tb_menu',(SELECT count(*) FROM tb_menu),
  'tb_code',(SELECT count(*) FROM tb_code),
  'tb_auth_menu_adm',(SELECT count(*) FROM tb_auth_menu_adm),
  'tb_user',(SELECT count(*) FROM tb_user),
  'tb_user_role',(SELECT count(*) FROM tb_user_role),
  'tb_system_settings',(SELECT count(*) FROM tb_system_settings)),
'issues',jsonb_build_object(
  'missing_roles', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.code AS item FROM required_roles r WHERE NOT EXISTS(SELECT 1 FROM tb_role t WHERE t.code=r.code)) q),'[]'::jsonb),
  'missing_auth_groups', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.code AS item FROM required_roles r WHERE NOT EXISTS(SELECT 1 FROM tb_auth t WHERE t.auth_nm=r.code AND t.use_yn='Y')) q),'[]'::jsonb),
  'missing_menus', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.url AS item FROM required_menus r WHERE NOT EXISTS(SELECT 1 FROM tb_menu t WHERE t.menu_url=r.url AND t.use_yn='Y')) q),'[]'::jsonb),
  'missing_code_groups', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.group_key AS item FROM required_groups r WHERE NOT EXISTS(SELECT 1 FROM tb_code t WHERE t.code_group=r.group_key AND t.code_depth IN(1,2) AND t.use_yn='Y')) q),'[]'::jsonb),
  'missing_code_values', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.parent_key||':'||r.code_key AS item FROM required_values r WHERE NOT EXISTS(SELECT 1 FROM tb_code c JOIN tb_code p ON p.code_no=c.p_code_no WHERE p.code_group=r.parent_key AND p.use_yn='Y' AND c.code_group=r.code_key AND c.code_val IS NOT DISTINCT FROM r.code_value AND c.code_depth=3 AND c.use_yn='Y')) q),'[]'::jsonb),
  'missing_menu_permissions', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT r.auth_name||':'||coalesce(r.menu_url,r.root_name) AS item FROM required_grants r WHERE NOT EXISTS(SELECT 1 FROM tb_auth a JOIN tb_auth_menu_adm g ON g.auth_no=a.auth_no JOIN tb_menu m ON m.menu_no=g.menu_no WHERE a.auth_nm=r.auth_name AND a.use_yn='Y' AND g.use_yn='Y' AND m.use_yn='Y' AND ((r.menu_url IS NOT NULL AND m.menu_url=r.menu_url) OR (r.menu_url IS NULL AND m.p_menu_no=0 AND m.menu_nm=r.root_name)) AND g.select_yn=r.select_yn AND g.insert_yn=r.insert_yn AND g.update_yn=r.update_yn AND g.delete_yn=r.delete_yn AND g.proc_yn=r.proc_yn)) q),'[]'::jsonb),
  'orphan_menus', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT m.menu_no::text AS item FROM tb_menu m WHERE m.p_menu_no<>0 AND NOT EXISTS(SELECT 1 FROM tb_menu p WHERE p.menu_no=m.p_menu_no)) q),'[]'::jsonb),
  'orphan_codes', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT c.code_no::text AS item FROM tb_code c WHERE c.p_code_no<>0 AND NOT EXISTS(SELECT 1 FROM tb_code p WHERE p.code_no=c.p_code_no)) q),'[]'::jsonb),
  'missing_settings', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT 'SYSTEM_SETTINGS' AS item WHERE NOT EXISTS(SELECT 1 FROM tb_system_settings WHERE id=1)) q),'[]'::jsonb),
  'missing_local_admin', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM (SELECT 'LOCAL_ADMIN' AS item WHERE EXISTS(SELECT 1 FROM tb_system_settings WHERE id=1 AND operation_mode='LOCAL') AND NOT EXISTS(SELECT 1 FROM tb_user u JOIN tb_user_role ur ON ur.user_no=u.user_no JOIN tb_role r ON r.role_no=ur.role_no WHERE u.auth_source='LOCAL' AND u.use_yn='Y' AND r.code='ADMIN')) q),'[]'::jsonb)));
COMMIT;
