"""Build reviewable seed/check SQL from the clean-install manifest; never connect to a DB.

The normal installation source remains Flyway. Python is needed only to regenerate these
two checked-in SQL files after reviewing an updated clean-install manifest.
"""

import json
from pathlib import Path


SEED = Path(__file__).resolve().parents[1] / "deploy/seed"
FIELDS = {
    "tb_role": ["code", "description"],
    "tb_auth": ["auth_no", "auth_nm", "auth_dc", "sort_order", "use_yn"],
    "tb_menu": ["menu_no", "p_menu_no", "menu_nm", "menu_type", "menu_depth", "sort_order",
                "target_blank_yn", "menu_url", "open_yn", "use_yn"],
    "tb_code": ["code_no", "p_code_no", "code_group", "code_nm", "code_val", "code_dc",
                "code_depth", "sort_order", "use_yn"],
    "tb_auth_menu_adm": ["auth_no", "menu_no", "p_menu_no", "select_yn", "insert_yn",
                         "update_yn", "delete_yn", "proc_yn", "use_yn"],
}


def literal(value):
    if value is None:
        return "NULL"
    if type(value) is int:
        return str(value)
    if not isinstance(value, str) or "$basic_data$" in value:
        raise ValueError("Unexpected seed value")
    return "'" + value.replace("'", "''") + "'"


def values(rows):
    return ",\n    ".join("(" + ", ".join(map(literal, row)) + ")" for row in rows)


def main():
    manifest = json.loads((SEED / "basic-data-manifest.json").read_text(encoding="utf-8"))
    data = manifest["tables"]
    if manifest["columns"] != FIELDS or set(data) != set(FIELDS):
        raise ValueError("Only the explicitly allowed reference-data fields can be exported")
    for table, columns in FIELDS.items():
        if not data[table] or any(set(row) != set(columns) for row in data[table]):
            raise ValueError(f"Invalid manifest rows: {table}")
    menus = {m["menu_no"]: m for m in data["tb_menu"]}
    codes = {c["code_no"]: c for c in data["tb_code"]}
    auths = {a["auth_no"]: a for a in data["tb_auth"]}
    for mapping, rows, parent in [(menus, data["tb_menu"], "p_menu_no"), (codes, data["tb_code"], "p_code_no")]:
        assert len(mapping) == len(rows), "Duplicate ID"
        assert all(row[parent] == 0 or row[parent] in mapping for row in rows), "Missing parent"
    assert {r["code"] for r in data["tb_role"]} == {"ADMIN", "OPERATOR", "USER"}
    assert {r["auth_nm"] for r in data["tb_auth"]} == {"ADMIN", "OPERATOR", "USER"}
    for grant in data["tb_auth_menu_adm"]:
        assert grant["auth_no"] in auths and grant["menu_no"] in menus
        assert grant["p_menu_no"] == menus[grant["menu_no"]]["p_menu_no"]

    seed = ["-- Generated by tools/build_basic_data.py from the clean V44 manifest.",
            "-- Run only after Flyway V44+. No users, credentials or business data are copied.",
            "-- Existing populated CMS data is a no-op; partially empty CMS data is rejected.",
            "BEGIN;", "SET LOCAL search_path TO cleverchat_dev, public;",
            "SET LOCAL lock_timeout = '10s';",
            "LOCK TABLE tb_role, tb_auth, tb_menu, tb_code, tb_auth_menu_adm IN SHARE ROW EXCLUSIVE MODE;",
            "DO $basic_data$", "DECLARE nonempty_tables integer;", "BEGIN",
            "  SELECT (EXISTS(SELECT 1 FROM tb_auth))::int + (EXISTS(SELECT 1 FROM tb_menu))::int",
            "       + (EXISTS(SELECT 1 FROM tb_code))::int + (EXISTS(SELECT 1 FROM tb_auth_menu_adm))::int",
            "  INTO nonempty_tables;",
            "  IF nonempty_tables = 4 THEN",
            "    RAISE NOTICE 'Existing CMS data retained. Run check-basic-data.sql to inspect it.';",
            "    RETURN;",
            "  ELSIF nonempty_tables <> 0 THEN",
            "    RAISE EXCEPTION 'Partially populated CMS tables: no changes made. Review/restore the missing data.';",
            "  END IF;", ""]
    for table, columns in FIELDS.items():
        rows = [[row[column] for column in columns] for row in data[table]]
        if table == "tb_role":
            seed += ["  INSERT INTO tb_role(code,description)",
                     "  SELECT v.code,v.description FROM (VALUES\n    " + values(rows) + ") v(code,description)",
                     "  WHERE NOT EXISTS(SELECT 1 FROM tb_role r WHERE r.code=v.code)",
                     "  ON CONFLICT(code) DO NOTHING;", ""]
        else:
            fields = columns + ["frst_regr_empno", "lst_chgr_empno"]
            seed += ["  INSERT INTO " + table + "(" + ",".join(fields) + ") VALUES",
                     "    " + values([row + ["basic-data", "basic-data"] for row in rows]) + ";", ""]
    seed += ["  INSERT INTO tb_system_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;", ""]
    for sequence, table, column in [("seq_tb_auth_auth_no", "tb_auth", "auth_no"),
                                    ("seq_tb_menu_menu_no", "tb_menu", "menu_no"),
                                    ("tb_code_code_no_seq", "tb_code", "code_no")]:
        seed += [f"  PERFORM setval('{sequence}', GREATEST(s.last_value,(SELECT max({column}) FROM {table})),",
                 f"      s.is_called OR (SELECT max({column}) FROM {table}) >= s.last_value) FROM {sequence} s;"]
    seed += ["  RAISE NOTICE 'Default menus/codes/roles/permissions initialized. User accounts were not modified.';",
             "END $basic_data$;", "COMMIT;", ""]
    (SEED / "basic-data.sql").write_text("\n".join(seed), encoding="utf-8")

    flags = ["select_yn", "insert_yn", "update_yn", "delete_yn", "proc_yn"]
    grants = [[auths[g["auth_no"]]["auth_nm"], menus[g["menu_no"]]["menu_url"],
               menus[g["menu_no"]]["menu_nm"] if menus[g["menu_no"]]["menu_url"] is None else None,
               *[g[f] for f in flags]] for g in data["tb_auth_menu_adm"]]
    groups = [[c["code_group"]] for c in data["tb_code"] if c["code_depth"] < 3]
    details = [[codes[c["p_code_no"]]["code_group"], c["code_group"], c["code_val"]]
               for c in data["tb_code"] if c["code_depth"] == 3]
    ctes = ["required_roles(code) AS (VALUES\n    " + values([[r["code"]] for r in data["tb_role"]]) + ")",
            "required_menus(url) AS (VALUES\n    " + values([[m["menu_url"]] for m in data["tb_menu"] if m["menu_url"]]) + ")",
            "required_groups(group_key) AS (VALUES\n    " + values(groups) + ")",
            "required_values(parent_key,code_key,code_value) AS (VALUES\n    " + values(details) + ")",
            "required_grants(auth_name,menu_url,root_name," + ",".join(flags) + ") AS (VALUES\n    " + values(grants) + ")"]
    issues = {
        "missing_roles": "SELECT r.code AS item FROM required_roles r WHERE NOT EXISTS(SELECT 1 FROM tb_role t WHERE t.code=r.code)",
        "missing_auth_groups": "SELECT r.code AS item FROM required_roles r WHERE NOT EXISTS(SELECT 1 FROM tb_auth t WHERE t.auth_nm=r.code AND t.use_yn='Y')",
        "missing_menus": "SELECT r.url AS item FROM required_menus r WHERE NOT EXISTS(SELECT 1 FROM tb_menu t WHERE t.menu_url=r.url AND t.use_yn='Y')",
        "missing_code_groups": "SELECT r.group_key AS item FROM required_groups r WHERE NOT EXISTS(SELECT 1 FROM tb_code t WHERE t.code_group=r.group_key AND t.code_depth IN(1,2) AND t.use_yn='Y')",
        "missing_code_values": "SELECT r.parent_key||':'||r.code_key AS item FROM required_values r WHERE NOT EXISTS(SELECT 1 FROM tb_code c JOIN tb_code p ON p.code_no=c.p_code_no WHERE p.code_group=r.parent_key AND p.use_yn='Y' AND c.code_group=r.code_key AND c.code_val IS NOT DISTINCT FROM r.code_value AND c.code_depth=3 AND c.use_yn='Y')",
        "missing_menu_permissions": "SELECT r.auth_name||':'||coalesce(r.menu_url,r.root_name) AS item FROM required_grants r WHERE NOT EXISTS(SELECT 1 FROM tb_auth a JOIN tb_auth_menu_adm g ON g.auth_no=a.auth_no JOIN tb_menu m ON m.menu_no=g.menu_no WHERE a.auth_nm=r.auth_name AND a.use_yn='Y' AND g.use_yn='Y' AND m.use_yn='Y' AND ((r.menu_url IS NOT NULL AND m.menu_url=r.menu_url) OR (r.menu_url IS NULL AND m.p_menu_no=0 AND m.menu_nm=r.root_name)) AND " + " AND ".join("g."+f+"=r."+f for f in flags) + ")",
        "orphan_menus": "SELECT m.menu_no::text AS item FROM tb_menu m WHERE m.p_menu_no<>0 AND NOT EXISTS(SELECT 1 FROM tb_menu p WHERE p.menu_no=m.p_menu_no)",
        "orphan_codes": "SELECT c.code_no::text AS item FROM tb_code c WHERE c.p_code_no<>0 AND NOT EXISTS(SELECT 1 FROM tb_code p WHERE p.code_no=c.p_code_no)",
        "missing_settings": "SELECT 'SYSTEM_SETTINGS' AS item WHERE NOT EXISTS(SELECT 1 FROM tb_system_settings WHERE id=1)",
        "missing_local_admin": "SELECT 'LOCAL_ADMIN' AS item WHERE EXISTS(SELECT 1 FROM tb_system_settings WHERE id=1 AND operation_mode='LOCAL') AND NOT EXISTS(SELECT 1 FROM tb_user u JOIN tb_user_role ur ON ur.user_no=u.user_no JOIN tb_role r ON r.role_no=ur.role_no WHERE u.auth_source='LOCAL' AND u.use_yn='Y' AND r.code='ADMIN')",
    }
    pairs = ["'"+name+"', COALESCE((SELECT jsonb_agg(item ORDER BY item) FROM ("+sql+") q),'[]'::jsonb)" for name,sql in issues.items()]
    counts = [f"'{table}',(SELECT count(*) FROM {table})" for table in [*FIELDS, "tb_user", "tb_user_role", "tb_system_settings"]]
    check = ["-- Read-only validation against the clean V44 baseline. Never restores disabled permissions.",
             "-- Existing customized data may differ; review differences, do not blindly reseed it.",
             "BEGIN READ ONLY;", "SET LOCAL search_path TO cleverchat_dev, public;", "WITH " + ",\n".join(ctes),
             "SELECT jsonb_build_object('baseline','V44','counts',jsonb_build_object(\n  " + ",\n  ".join(counts) + "),",
             "'issues',jsonb_build_object(\n  " + ",\n  ".join(pairs) + "));", "COMMIT;", ""]
    (SEED / "check-basic-data.sql").write_text("\n".join(check), encoding="utf-8")
    print("Generated basic-data.sql and check-basic-data.sql from reference data only.")


if __name__ == "__main__":
    main()
